# Generated by Django 6.0.4 on 2026-05-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Monthly base salary', max_digits=10),
        ),
    ]
