# Generated by Django 5.2.14 on 2026-06-03 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(blank=True, help_text='For unregistered leads', max_length=150, null=True)),
                ('lead_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('lead_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(default='Solar System Proposal', max_length=200)),
                ('solar_capacity_kw', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('material_breakdown', models.TextField(blank=True, help_text='Details of panels, inverters, etc.')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Client'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'role': 'CUSTOMER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
