# Generated by Django 5.2.14 on 2026-06-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
