# Generated by Django 6.0.4 on 2026-06-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
