# Generated by Django 5.2.14 on 2026-06-10 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification_notificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarinstallationproject',
            name='closing_date',
            field=models.DateField(blank=True, help_text='Date when project was closed/completed', null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationproject',
            name='inverter_brand',
            field=models.CharField(blank=True, help_text='Inverter Brand', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationproject',
            name='inverter_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Inverter Capacity in kW', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(help_text='Scheduled date for the 6-month inspection')),
                ('inspection_date', models.DateField(blank=True, help_text='Date when inspection was actually performed', null=True)),
                ('panel_check', models.BooleanField(default=False, verbose_name='Solar Panels clean and secure')),
                ('inverter_check', models.BooleanField(default=False, verbose_name='Inverter operating correctly')),
                ('wiring_check', models.BooleanField(default=False, verbose_name='Wiring and connections intact')),
                ('mounting_check', models.BooleanField(default=False, verbose_name='Mounting structure stable')),
                ('performance_check', models.BooleanField(default=False, verbose_name='System performance verified')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed')], default='SCHEDULED', max_length=20)),
                ('has_issues', models.BooleanField(default=False, help_text='Were issues identified during the inspection?')),
                ('issue_details', models.TextField(blank=True, help_text='Detailed description of the issues reported', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, limit_choices_to={'role': 'STAFF'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_inspections', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.solarinstallationproject')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
