# Generated by Django 6.0.4 on 2026-06-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_solarinstallationproject_closing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Inverter Brand', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Inverter Model', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Inverter Serial Number (S.No)', max_length=100, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Inverter Capacity in kW', max_digits=6, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inverter', to='core.solarinstallationproject')),
            ],
        ),
    ]
