# Generated by Django 6.0.4 on 2026-06-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_inverter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarinstallationproject',
            name='inverter_brand',
        ),
        migrations.RemoveField(
            model_name='solarinstallationproject',
            name='inverter_capacity',
        ),
    ]
