# Generated by Django 6.0.4 on 2026-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_solarinstallationproject_inverter_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_dc_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('panel_dc_max', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('inverter_ac_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('inverter_ac_max', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('wiring_protection_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wiring_protection_max', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('earthing_resistance_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('earthing_resistance_max', models.DecimalField(decimal_places=2, default=10.0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='earthing_resistance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured Earthing Resistance (ohms)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inverter_ac_output',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured Inverter AC Output (kW)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='panel_dc_output',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured Solar Panel DC Output (kW)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='wiring_protection',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Measured Wiring & Protection drop/value', max_digits=10, null=True),
        ),
    ]
