# Generated by Django 6.0.4 on 2026-06-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_inspectionlimit_inspection_earthing_resistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Staff'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
