# Generated by Django 6.0.4 on 2026-06-21 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_inspection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='warranty_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inverter',
            name='warranty_terms_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inverter',
            name='warranty_terms_text',
            field=models.TextField(blank=True, help_text='Warranty terms and conditions agreement text', null=True),
        ),
        migrations.AddField(
            model_name='solarinstallationproject',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Super User'), ('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('STAFF', 'Staff'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Client')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Solar Panel Brand', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='Solar Panel Model', max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='Solar Panel Serial Number (S.No)', max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, help_text='Number of Solar Panels', null=True)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('warranty_terms_agreed', models.BooleanField(default=False)),
                ('warranty_terms_text', models.TextField(blank=True, help_text='Warranty terms and conditions agreement text', null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_panel', to='core.solarinstallationproject')),
            ],
        ),
    ]
